// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Kill.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Kill.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

turtlesim::srv::Kill_Request::Kill_Request()
{
    // m_name com.eprosima.idl.parser.typecode.StringTypeCode@569cfc36
    m_name ="";

}

turtlesim::srv::Kill_Request::~Kill_Request()
{
}

turtlesim::srv::Kill_Request::Kill_Request(
        const Kill_Request& x)
{
    m_name = x.m_name;
}

turtlesim::srv::Kill_Request::Kill_Request(
        Kill_Request&& x)
{
    m_name = std::move(x.m_name);
}

turtlesim::srv::Kill_Request& turtlesim::srv::Kill_Request::operator =(
        const Kill_Request& x)
{

    m_name = x.m_name;

    return *this;
}

turtlesim::srv::Kill_Request& turtlesim::srv::Kill_Request::operator =(
        Kill_Request&& x)
{

    m_name = std::move(x.m_name);

    return *this;
}

bool turtlesim::srv::Kill_Request::operator ==(
        const Kill_Request& x) const
{

    return (m_name == x.m_name);
}

bool turtlesim::srv::Kill_Request::operator !=(
        const Kill_Request& x) const
{
    return !(*this == x);
}

size_t turtlesim::srv::Kill_Request::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    return current_alignment - initial_alignment;
}

size_t turtlesim::srv::Kill_Request::getCdrSerializedSize(
        const turtlesim::srv::Kill_Request& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.name().size() + 1;

    return current_alignment - initial_alignment;
}

void turtlesim::srv::Kill_Request::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_name;

}

void turtlesim::srv::Kill_Request::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_name;
}

/*!
 * @brief This function copies the value in member name
 * @param _name New value to be copied in member name
 */
void turtlesim::srv::Kill_Request::name(
        const std::string& _name)
{
    m_name = _name;
}

/*!
 * @brief This function moves the value in member name
 * @param _name New value to be moved in member name
 */
void turtlesim::srv::Kill_Request::name(
        std::string&& _name)
{
    m_name = std::move(_name);
}

/*!
 * @brief This function returns a constant reference to member name
 * @return Constant reference to member name
 */
const std::string& turtlesim::srv::Kill_Request::name() const
{
    return m_name;
}

/*!
 * @brief This function returns a reference to member name
 * @return Reference to member name
 */
std::string& turtlesim::srv::Kill_Request::name()
{
    return m_name;
}

size_t turtlesim::srv::Kill_Request::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool turtlesim::srv::Kill_Request::isKeyDefined()
{
    return false;
}

void turtlesim::srv::Kill_Request::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}

turtlesim::srv::Kill_Response::Kill_Response()
{
    // m_structure_needs_at_least_one_member com.eprosima.idl.parser.typecode.PrimitiveTypeCode@782663d3
    m_structure_needs_at_least_one_member = 0;

}

turtlesim::srv::Kill_Response::~Kill_Response()
{
}

turtlesim::srv::Kill_Response::Kill_Response(
        const Kill_Response& x)
{
    m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;
}

turtlesim::srv::Kill_Response::Kill_Response(
        Kill_Response&& x)
{
    m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;
}

turtlesim::srv::Kill_Response& turtlesim::srv::Kill_Response::operator =(
        const Kill_Response& x)
{

    m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;

    return *this;
}

turtlesim::srv::Kill_Response& turtlesim::srv::Kill_Response::operator =(
        Kill_Response&& x)
{

    m_structure_needs_at_least_one_member = x.m_structure_needs_at_least_one_member;

    return *this;
}

bool turtlesim::srv::Kill_Response::operator ==(
        const Kill_Response& x) const
{

    return (m_structure_needs_at_least_one_member == x.m_structure_needs_at_least_one_member);
}

bool turtlesim::srv::Kill_Response::operator !=(
        const Kill_Response& x) const
{
    return !(*this == x);
}

size_t turtlesim::srv::Kill_Response::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

size_t turtlesim::srv::Kill_Response::getCdrSerializedSize(
        const turtlesim::srv::Kill_Response& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

void turtlesim::srv::Kill_Response::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_structure_needs_at_least_one_member;

}

void turtlesim::srv::Kill_Response::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_structure_needs_at_least_one_member;
}

/*!
 * @brief This function sets a value in member structure_needs_at_least_one_member
 * @param _structure_needs_at_least_one_member New value for member structure_needs_at_least_one_member
 */
void turtlesim::srv::Kill_Response::structure_needs_at_least_one_member(
        uint8_t _structure_needs_at_least_one_member)
{
    m_structure_needs_at_least_one_member = _structure_needs_at_least_one_member;
}

/*!
 * @brief This function returns the value of member structure_needs_at_least_one_member
 * @return Value of member structure_needs_at_least_one_member
 */
uint8_t turtlesim::srv::Kill_Response::structure_needs_at_least_one_member() const
{
    return m_structure_needs_at_least_one_member;
}

/*!
 * @brief This function returns a reference to member structure_needs_at_least_one_member
 * @return Reference to member structure_needs_at_least_one_member
 */
uint8_t& turtlesim::srv::Kill_Response::structure_needs_at_least_one_member()
{
    return m_structure_needs_at_least_one_member;
}


size_t turtlesim::srv::Kill_Response::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool turtlesim::srv::Kill_Response::isKeyDefined()
{
    return false;
}

void turtlesim::srv::Kill_Response::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}


