// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SetPen.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_TURTLESIM_SRV_SETPEN_H_
#define _FAST_DDS_GENERATED_TURTLESIM_SRV_SETPEN_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(SetPen_SOURCE)
#define SetPen_DllAPI __declspec( dllexport )
#else
#define SetPen_DllAPI __declspec( dllimport )
#endif // SetPen_SOURCE
#else
#define SetPen_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define SetPen_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace turtlesim {
    namespace srv {
        /*!
         * @brief This class represents the structure SetPen_Request defined by the user in the IDL file.
         * @ingroup SETPEN
         */
        class SetPen_Request
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport SetPen_Request();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~SetPen_Request();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object turtlesim::srv::SetPen_Request that will be copied.
             */
            eProsima_user_DllExport SetPen_Request(
                    const SetPen_Request& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object turtlesim::srv::SetPen_Request that will be copied.
             */
            eProsima_user_DllExport SetPen_Request(
                    SetPen_Request&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object turtlesim::srv::SetPen_Request that will be copied.
             */
            eProsima_user_DllExport SetPen_Request& operator =(
                    const SetPen_Request& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object turtlesim::srv::SetPen_Request that will be copied.
             */
            eProsima_user_DllExport SetPen_Request& operator =(
                    SetPen_Request&& x);

            /*!
             * @brief Comparison operator.
             * @param x turtlesim::srv::SetPen_Request object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const SetPen_Request& x) const;

            /*!
             * @brief Comparison operator.
             * @param x turtlesim::srv::SetPen_Request object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const SetPen_Request& x) const;

            /*!
             * @brief This function sets a value in member r
             * @param _r New value for member r
             */
            eProsima_user_DllExport void r(
                    uint8_t _r);

            /*!
             * @brief This function returns the value of member r
             * @return Value of member r
             */
            eProsima_user_DllExport uint8_t r() const;

            /*!
             * @brief This function returns a reference to member r
             * @return Reference to member r
             */
            eProsima_user_DllExport uint8_t& r();

            /*!
             * @brief This function sets a value in member g
             * @param _g New value for member g
             */
            eProsima_user_DllExport void g(
                    uint8_t _g);

            /*!
             * @brief This function returns the value of member g
             * @return Value of member g
             */
            eProsima_user_DllExport uint8_t g() const;

            /*!
             * @brief This function returns a reference to member g
             * @return Reference to member g
             */
            eProsima_user_DllExport uint8_t& g();

            /*!
             * @brief This function sets a value in member b
             * @param _b New value for member b
             */
            eProsima_user_DllExport void b(
                    uint8_t _b);

            /*!
             * @brief This function returns the value of member b
             * @return Value of member b
             */
            eProsima_user_DllExport uint8_t b() const;

            /*!
             * @brief This function returns a reference to member b
             * @return Reference to member b
             */
            eProsima_user_DllExport uint8_t& b();

            /*!
             * @brief This function sets a value in member width
             * @param _width New value for member width
             */
            eProsima_user_DllExport void width(
                    uint8_t _width);

            /*!
             * @brief This function returns the value of member width
             * @return Value of member width
             */
            eProsima_user_DllExport uint8_t width() const;

            /*!
             * @brief This function returns a reference to member width
             * @return Reference to member width
             */
            eProsima_user_DllExport uint8_t& width();

            /*!
             * @brief This function sets a value in member off
             * @param _off New value for member off
             */
            eProsima_user_DllExport void off(
                    uint8_t _off);

            /*!
             * @brief This function returns the value of member off
             * @return Value of member off
             */
            eProsima_user_DllExport uint8_t off() const;

            /*!
             * @brief This function returns a reference to member off
             * @return Reference to member off
             */
            eProsima_user_DllExport uint8_t& off();


            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const turtlesim::srv::SetPen_Request& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            uint8_t m_r;
            uint8_t m_g;
            uint8_t m_b;
            uint8_t m_width;
            uint8_t m_off;
        };
        /*!
         * @brief This class represents the structure SetPen_Response defined by the user in the IDL file.
         * @ingroup SETPEN
         */
        class SetPen_Response
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport SetPen_Response();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~SetPen_Response();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object turtlesim::srv::SetPen_Response that will be copied.
             */
            eProsima_user_DllExport SetPen_Response(
                    const SetPen_Response& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object turtlesim::srv::SetPen_Response that will be copied.
             */
            eProsima_user_DllExport SetPen_Response(
                    SetPen_Response&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object turtlesim::srv::SetPen_Response that will be copied.
             */
            eProsima_user_DllExport SetPen_Response& operator =(
                    const SetPen_Response& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object turtlesim::srv::SetPen_Response that will be copied.
             */
            eProsima_user_DllExport SetPen_Response& operator =(
                    SetPen_Response&& x);

            /*!
             * @brief Comparison operator.
             * @param x turtlesim::srv::SetPen_Response object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const SetPen_Response& x) const;

            /*!
             * @brief Comparison operator.
             * @param x turtlesim::srv::SetPen_Response object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const SetPen_Response& x) const;

            /*!
             * @brief This function sets a value in member structure_needs_at_least_one_member
             * @param _structure_needs_at_least_one_member New value for member structure_needs_at_least_one_member
             */
            eProsima_user_DllExport void structure_needs_at_least_one_member(
                    uint8_t _structure_needs_at_least_one_member);

            /*!
             * @brief This function returns the value of member structure_needs_at_least_one_member
             * @return Value of member structure_needs_at_least_one_member
             */
            eProsima_user_DllExport uint8_t structure_needs_at_least_one_member() const;

            /*!
             * @brief This function returns a reference to member structure_needs_at_least_one_member
             * @return Reference to member structure_needs_at_least_one_member
             */
            eProsima_user_DllExport uint8_t& structure_needs_at_least_one_member();


            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const turtlesim::srv::SetPen_Response& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            uint8_t m_structure_needs_at_least_one_member;
        };
    } // namespace srv
} // namespace turtlesim

#endif // _FAST_DDS_GENERATED_TURTLESIM_SRV_SETPEN_H_