// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CollisionMonitorState.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_NAV2_MSGS_MSG_COLLISIONMONITORSTATE_H_
#define _FAST_DDS_GENERATED_NAV2_MSGS_MSG_COLLISIONMONITORSTATE_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CollisionMonitorState_SOURCE)
#define CollisionMonitorState_DllAPI __declspec( dllexport )
#else
#define CollisionMonitorState_DllAPI __declspec( dllimport )
#endif // CollisionMonitorState_SOURCE
#else
#define CollisionMonitorState_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CollisionMonitorState_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace nav2_msgs {
    namespace msg {
        namespace CollisionMonitorState_Constants {
            const uint8_t DO_NOTHING = 0;
            const uint8_t STOP = 1;
            const uint8_t SLOWDOWN = 2;
            const uint8_t APPROACH = 3;
        } // namespace CollisionMonitorState_Constants
        /*!
         * @brief This class represents the structure CollisionMonitorState defined by the user in the IDL file.
         * @ingroup COLLISIONMONITORSTATE
         */
        class CollisionMonitorState
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport CollisionMonitorState();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~CollisionMonitorState();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object nav2_msgs::msg::CollisionMonitorState that will be copied.
             */
            eProsima_user_DllExport CollisionMonitorState(
                    const CollisionMonitorState& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object nav2_msgs::msg::CollisionMonitorState that will be copied.
             */
            eProsima_user_DllExport CollisionMonitorState(
                    CollisionMonitorState&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object nav2_msgs::msg::CollisionMonitorState that will be copied.
             */
            eProsima_user_DllExport CollisionMonitorState& operator =(
                    const CollisionMonitorState& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object nav2_msgs::msg::CollisionMonitorState that will be copied.
             */
            eProsima_user_DllExport CollisionMonitorState& operator =(
                    CollisionMonitorState&& x);

            /*!
             * @brief Comparison operator.
             * @param x nav2_msgs::msg::CollisionMonitorState object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const CollisionMonitorState& x) const;

            /*!
             * @brief Comparison operator.
             * @param x nav2_msgs::msg::CollisionMonitorState object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const CollisionMonitorState& x) const;

            /*!
             * @brief This function sets a value in member action_type
             * @param _action_type New value for member action_type
             */
            eProsima_user_DllExport void action_type(
                    uint8_t _action_type);

            /*!
             * @brief This function returns the value of member action_type
             * @return Value of member action_type
             */
            eProsima_user_DllExport uint8_t action_type() const;

            /*!
             * @brief This function returns a reference to member action_type
             * @return Reference to member action_type
             */
            eProsima_user_DllExport uint8_t& action_type();

            /*!
             * @brief This function copies the value in member polygon_name
             * @param _polygon_name New value to be copied in member polygon_name
             */
            eProsima_user_DllExport void polygon_name(
                    const std::string& _polygon_name);

            /*!
             * @brief This function moves the value in member polygon_name
             * @param _polygon_name New value to be moved in member polygon_name
             */
            eProsima_user_DllExport void polygon_name(
                    std::string&& _polygon_name);

            /*!
             * @brief This function returns a constant reference to member polygon_name
             * @return Constant reference to member polygon_name
             */
            eProsima_user_DllExport const std::string& polygon_name() const;

            /*!
             * @brief This function returns a reference to member polygon_name
             * @return Reference to member polygon_name
             */
            eProsima_user_DllExport std::string& polygon_name();

            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const nav2_msgs::msg::CollisionMonitorState& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            uint8_t m_action_type;
            std::string m_polygon_name;
        };
    } // namespace msg
} // namespace nav2_msgs

#endif // _FAST_DDS_GENERATED_NAV2_MSGS_MSG_COLLISIONMONITORSTATE_H_