// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ConfigLogger.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_LOGGING_DEMO_SRV_CONFIGLOGGER_H_
#define _FAST_DDS_GENERATED_LOGGING_DEMO_SRV_CONFIGLOGGER_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ConfigLogger_SOURCE)
#define ConfigLogger_DllAPI __declspec( dllexport )
#else
#define ConfigLogger_DllAPI __declspec( dllimport )
#endif // ConfigLogger_SOURCE
#else
#define ConfigLogger_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ConfigLogger_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace logging_demo {
    namespace srv {
        /*!
         * @brief This class represents the structure ConfigLogger_Request defined by the user in the IDL file.
         * @ingroup CONFIGLOGGER
         */
        class ConfigLogger_Request
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport ConfigLogger_Request();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~ConfigLogger_Request();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object logging_demo::srv::ConfigLogger_Request that will be copied.
             */
            eProsima_user_DllExport ConfigLogger_Request(
                    const ConfigLogger_Request& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object logging_demo::srv::ConfigLogger_Request that will be copied.
             */
            eProsima_user_DllExport ConfigLogger_Request(
                    ConfigLogger_Request&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object logging_demo::srv::ConfigLogger_Request that will be copied.
             */
            eProsima_user_DllExport ConfigLogger_Request& operator =(
                    const ConfigLogger_Request& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object logging_demo::srv::ConfigLogger_Request that will be copied.
             */
            eProsima_user_DllExport ConfigLogger_Request& operator =(
                    ConfigLogger_Request&& x);

            /*!
             * @brief Comparison operator.
             * @param x logging_demo::srv::ConfigLogger_Request object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const ConfigLogger_Request& x) const;

            /*!
             * @brief Comparison operator.
             * @param x logging_demo::srv::ConfigLogger_Request object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const ConfigLogger_Request& x) const;

            /*!
             * @brief This function copies the value in member logger_name
             * @param _logger_name New value to be copied in member logger_name
             */
            eProsima_user_DllExport void logger_name(
                    const std::string& _logger_name);

            /*!
             * @brief This function moves the value in member logger_name
             * @param _logger_name New value to be moved in member logger_name
             */
            eProsima_user_DllExport void logger_name(
                    std::string&& _logger_name);

            /*!
             * @brief This function returns a constant reference to member logger_name
             * @return Constant reference to member logger_name
             */
            eProsima_user_DllExport const std::string& logger_name() const;

            /*!
             * @brief This function returns a reference to member logger_name
             * @return Reference to member logger_name
             */
            eProsima_user_DllExport std::string& logger_name();
            /*!
             * @brief This function copies the value in member level
             * @param _level New value to be copied in member level
             */
            eProsima_user_DllExport void level(
                    const std::string& _level);

            /*!
             * @brief This function moves the value in member level
             * @param _level New value to be moved in member level
             */
            eProsima_user_DllExport void level(
                    std::string&& _level);

            /*!
             * @brief This function returns a constant reference to member level
             * @return Constant reference to member level
             */
            eProsima_user_DllExport const std::string& level() const;

            /*!
             * @brief This function returns a reference to member level
             * @return Reference to member level
             */
            eProsima_user_DllExport std::string& level();

            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const logging_demo::srv::ConfigLogger_Request& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            std::string m_logger_name;
            std::string m_level;
        };
        /*!
         * @brief This class represents the structure ConfigLogger_Response defined by the user in the IDL file.
         * @ingroup CONFIGLOGGER
         */
        class ConfigLogger_Response
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport ConfigLogger_Response();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~ConfigLogger_Response();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object logging_demo::srv::ConfigLogger_Response that will be copied.
             */
            eProsima_user_DllExport ConfigLogger_Response(
                    const ConfigLogger_Response& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object logging_demo::srv::ConfigLogger_Response that will be copied.
             */
            eProsima_user_DllExport ConfigLogger_Response(
                    ConfigLogger_Response&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object logging_demo::srv::ConfigLogger_Response that will be copied.
             */
            eProsima_user_DllExport ConfigLogger_Response& operator =(
                    const ConfigLogger_Response& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object logging_demo::srv::ConfigLogger_Response that will be copied.
             */
            eProsima_user_DllExport ConfigLogger_Response& operator =(
                    ConfigLogger_Response&& x);

            /*!
             * @brief Comparison operator.
             * @param x logging_demo::srv::ConfigLogger_Response object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const ConfigLogger_Response& x) const;

            /*!
             * @brief Comparison operator.
             * @param x logging_demo::srv::ConfigLogger_Response object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const ConfigLogger_Response& x) const;

            /*!
             * @brief This function sets a value in member success
             * @param _success New value for member success
             */
            eProsima_user_DllExport void success(
                    bool _success);

            /*!
             * @brief This function returns the value of member success
             * @return Value of member success
             */
            eProsima_user_DllExport bool success() const;

            /*!
             * @brief This function returns a reference to member success
             * @return Reference to member success
             */
            eProsima_user_DllExport bool& success();


            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const logging_demo::srv::ConfigLogger_Response& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            bool m_success;
        };
    } // namespace srv
} // namespace logging_demo

#endif // _FAST_DDS_GENERATED_LOGGING_DEMO_SRV_CONFIGLOGGER_H_