// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Vertices.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Vertices.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

pcl_msgs::msg::Vertices::Vertices()
{
    // m_vertices com.eprosima.idl.parser.typecode.SequenceTypeCode@19dc67c2


}

pcl_msgs::msg::Vertices::~Vertices()
{
}

pcl_msgs::msg::Vertices::Vertices(
        const Vertices& x)
{
    m_vertices = x.m_vertices;
}

pcl_msgs::msg::Vertices::Vertices(
        Vertices&& x)
{
    m_vertices = std::move(x.m_vertices);
}

pcl_msgs::msg::Vertices& pcl_msgs::msg::Vertices::operator =(
        const Vertices& x)
{

    m_vertices = x.m_vertices;

    return *this;
}

pcl_msgs::msg::Vertices& pcl_msgs::msg::Vertices::operator =(
        Vertices&& x)
{

    m_vertices = std::move(x.m_vertices);

    return *this;
}

bool pcl_msgs::msg::Vertices::operator ==(
        const Vertices& x) const
{

    return (m_vertices == x.m_vertices);
}

bool pcl_msgs::msg::Vertices::operator !=(
        const Vertices& x) const
{
    return !(*this == x);
}

size_t pcl_msgs::msg::Vertices::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (100 * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t pcl_msgs::msg::Vertices::getCdrSerializedSize(
        const pcl_msgs::msg::Vertices& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.vertices().size() > 0)
    {
        current_alignment += (data.vertices().size() * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    }



    return current_alignment - initial_alignment;
}

void pcl_msgs::msg::Vertices::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_vertices;
}

void pcl_msgs::msg::Vertices::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_vertices;}

/*!
 * @brief This function copies the value in member vertices
 * @param _vertices New value to be copied in member vertices
 */
void pcl_msgs::msg::Vertices::vertices(
        const std::vector<uint32_t>& _vertices)
{
    m_vertices = _vertices;
}

/*!
 * @brief This function moves the value in member vertices
 * @param _vertices New value to be moved in member vertices
 */
void pcl_msgs::msg::Vertices::vertices(
        std::vector<uint32_t>&& _vertices)
{
    m_vertices = std::move(_vertices);
}

/*!
 * @brief This function returns a constant reference to member vertices
 * @return Constant reference to member vertices
 */
const std::vector<uint32_t>& pcl_msgs::msg::Vertices::vertices() const
{
    return m_vertices;
}

/*!
 * @brief This function returns a reference to member vertices
 * @return Reference to member vertices
 */
std::vector<uint32_t>& pcl_msgs::msg::Vertices::vertices()
{
    return m_vertices;
}

size_t pcl_msgs::msg::Vertices::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool pcl_msgs::msg::Vertices::isKeyDefined()
{
    return false;
}

void pcl_msgs::msg::Vertices::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}


