// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ProjectedMapInfo.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_MAP_MSGS_MSG_PROJECTEDMAPINFO_H_
#define _FAST_DDS_GENERATED_MAP_MSGS_MSG_PROJECTEDMAPINFO_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ProjectedMapInfo_SOURCE)
#define ProjectedMapInfo_DllAPI __declspec( dllexport )
#else
#define ProjectedMapInfo_DllAPI __declspec( dllimport )
#endif // ProjectedMapInfo_SOURCE
#else
#define ProjectedMapInfo_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ProjectedMapInfo_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace map_msgs {
    namespace msg {
        /*!
         * @brief This class represents the structure ProjectedMapInfo defined by the user in the IDL file.
         * @ingroup PROJECTEDMAPINFO
         */
        class ProjectedMapInfo
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport ProjectedMapInfo();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~ProjectedMapInfo();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object map_msgs::msg::ProjectedMapInfo that will be copied.
             */
            eProsima_user_DllExport ProjectedMapInfo(
                    const ProjectedMapInfo& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object map_msgs::msg::ProjectedMapInfo that will be copied.
             */
            eProsima_user_DllExport ProjectedMapInfo(
                    ProjectedMapInfo&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object map_msgs::msg::ProjectedMapInfo that will be copied.
             */
            eProsima_user_DllExport ProjectedMapInfo& operator =(
                    const ProjectedMapInfo& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object map_msgs::msg::ProjectedMapInfo that will be copied.
             */
            eProsima_user_DllExport ProjectedMapInfo& operator =(
                    ProjectedMapInfo&& x);

            /*!
             * @brief Comparison operator.
             * @param x map_msgs::msg::ProjectedMapInfo object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const ProjectedMapInfo& x) const;

            /*!
             * @brief Comparison operator.
             * @param x map_msgs::msg::ProjectedMapInfo object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const ProjectedMapInfo& x) const;

            /*!
             * @brief This function copies the value in member frame_id
             * @param _frame_id New value to be copied in member frame_id
             */
            eProsima_user_DllExport void frame_id(
                    const std::string& _frame_id);

            /*!
             * @brief This function moves the value in member frame_id
             * @param _frame_id New value to be moved in member frame_id
             */
            eProsima_user_DllExport void frame_id(
                    std::string&& _frame_id);

            /*!
             * @brief This function returns a constant reference to member frame_id
             * @return Constant reference to member frame_id
             */
            eProsima_user_DllExport const std::string& frame_id() const;

            /*!
             * @brief This function returns a reference to member frame_id
             * @return Reference to member frame_id
             */
            eProsima_user_DllExport std::string& frame_id();
            /*!
             * @brief This function sets a value in member x
             * @param _x New value for member x
             */
            eProsima_user_DllExport void x(
                    double _x);

            /*!
             * @brief This function returns the value of member x
             * @return Value of member x
             */
            eProsima_user_DllExport double x() const;

            /*!
             * @brief This function returns a reference to member x
             * @return Reference to member x
             */
            eProsima_user_DllExport double& x();

            /*!
             * @brief This function sets a value in member y
             * @param _y New value for member y
             */
            eProsima_user_DllExport void y(
                    double _y);

            /*!
             * @brief This function returns the value of member y
             * @return Value of member y
             */
            eProsima_user_DllExport double y() const;

            /*!
             * @brief This function returns a reference to member y
             * @return Reference to member y
             */
            eProsima_user_DllExport double& y();

            /*!
             * @brief This function sets a value in member width
             * @param _width New value for member width
             */
            eProsima_user_DllExport void width(
                    double _width);

            /*!
             * @brief This function returns the value of member width
             * @return Value of member width
             */
            eProsima_user_DllExport double width() const;

            /*!
             * @brief This function returns a reference to member width
             * @return Reference to member width
             */
            eProsima_user_DllExport double& width();

            /*!
             * @brief This function sets a value in member height
             * @param _height New value for member height
             */
            eProsima_user_DllExport void height(
                    double _height);

            /*!
             * @brief This function returns the value of member height
             * @return Value of member height
             */
            eProsima_user_DllExport double height() const;

            /*!
             * @brief This function returns a reference to member height
             * @return Reference to member height
             */
            eProsima_user_DllExport double& height();

            /*!
             * @brief This function sets a value in member min_z
             * @param _min_z New value for member min_z
             */
            eProsima_user_DllExport void min_z(
                    double _min_z);

            /*!
             * @brief This function returns the value of member min_z
             * @return Value of member min_z
             */
            eProsima_user_DllExport double min_z() const;

            /*!
             * @brief This function returns a reference to member min_z
             * @return Reference to member min_z
             */
            eProsima_user_DllExport double& min_z();

            /*!
             * @brief This function sets a value in member max_z
             * @param _max_z New value for member max_z
             */
            eProsima_user_DllExport void max_z(
                    double _max_z);

            /*!
             * @brief This function returns the value of member max_z
             * @return Value of member max_z
             */
            eProsima_user_DllExport double max_z() const;

            /*!
             * @brief This function returns a reference to member max_z
             * @return Reference to member max_z
             */
            eProsima_user_DllExport double& max_z();


            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const map_msgs::msg::ProjectedMapInfo& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            std::string m_frame_id;
            double m_x;
            double m_y;
            double m_width;
            double m_height;
            double m_min_z;
            double m_max_z;
        };
    } // namespace msg
} // namespace map_msgs

#endif // _FAST_DDS_GENERATED_MAP_MSGS_MSG_PROJECTEDMAPINFO_H_