// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file UpdateFilename.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "UpdateFilename.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

pcl_msgs::srv::UpdateFilename_Request::UpdateFilename_Request()
{
    // m_filename com.eprosima.idl.parser.typecode.StringTypeCode@569cfc36
    m_filename ="";

}

pcl_msgs::srv::UpdateFilename_Request::~UpdateFilename_Request()
{
}

pcl_msgs::srv::UpdateFilename_Request::UpdateFilename_Request(
        const UpdateFilename_Request& x)
{
    m_filename = x.m_filename;
}

pcl_msgs::srv::UpdateFilename_Request::UpdateFilename_Request(
        UpdateFilename_Request&& x)
{
    m_filename = std::move(x.m_filename);
}

pcl_msgs::srv::UpdateFilename_Request& pcl_msgs::srv::UpdateFilename_Request::operator =(
        const UpdateFilename_Request& x)
{

    m_filename = x.m_filename;

    return *this;
}

pcl_msgs::srv::UpdateFilename_Request& pcl_msgs::srv::UpdateFilename_Request::operator =(
        UpdateFilename_Request&& x)
{

    m_filename = std::move(x.m_filename);

    return *this;
}

bool pcl_msgs::srv::UpdateFilename_Request::operator ==(
        const UpdateFilename_Request& x) const
{

    return (m_filename == x.m_filename);
}

bool pcl_msgs::srv::UpdateFilename_Request::operator !=(
        const UpdateFilename_Request& x) const
{
    return !(*this == x);
}

size_t pcl_msgs::srv::UpdateFilename_Request::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    return current_alignment - initial_alignment;
}

size_t pcl_msgs::srv::UpdateFilename_Request::getCdrSerializedSize(
        const pcl_msgs::srv::UpdateFilename_Request& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.filename().size() + 1;

    return current_alignment - initial_alignment;
}

void pcl_msgs::srv::UpdateFilename_Request::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_filename;

}

void pcl_msgs::srv::UpdateFilename_Request::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_filename;
}

/*!
 * @brief This function copies the value in member filename
 * @param _filename New value to be copied in member filename
 */
void pcl_msgs::srv::UpdateFilename_Request::filename(
        const std::string& _filename)
{
    m_filename = _filename;
}

/*!
 * @brief This function moves the value in member filename
 * @param _filename New value to be moved in member filename
 */
void pcl_msgs::srv::UpdateFilename_Request::filename(
        std::string&& _filename)
{
    m_filename = std::move(_filename);
}

/*!
 * @brief This function returns a constant reference to member filename
 * @return Constant reference to member filename
 */
const std::string& pcl_msgs::srv::UpdateFilename_Request::filename() const
{
    return m_filename;
}

/*!
 * @brief This function returns a reference to member filename
 * @return Reference to member filename
 */
std::string& pcl_msgs::srv::UpdateFilename_Request::filename()
{
    return m_filename;
}

size_t pcl_msgs::srv::UpdateFilename_Request::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool pcl_msgs::srv::UpdateFilename_Request::isKeyDefined()
{
    return false;
}

void pcl_msgs::srv::UpdateFilename_Request::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}

pcl_msgs::srv::UpdateFilename_Response::UpdateFilename_Response()
{
    // m_success com.eprosima.idl.parser.typecode.PrimitiveTypeCode@12c8a2c0
    m_success = false;

}

pcl_msgs::srv::UpdateFilename_Response::~UpdateFilename_Response()
{
}

pcl_msgs::srv::UpdateFilename_Response::UpdateFilename_Response(
        const UpdateFilename_Response& x)
{
    m_success = x.m_success;
}

pcl_msgs::srv::UpdateFilename_Response::UpdateFilename_Response(
        UpdateFilename_Response&& x)
{
    m_success = x.m_success;
}

pcl_msgs::srv::UpdateFilename_Response& pcl_msgs::srv::UpdateFilename_Response::operator =(
        const UpdateFilename_Response& x)
{

    m_success = x.m_success;

    return *this;
}

pcl_msgs::srv::UpdateFilename_Response& pcl_msgs::srv::UpdateFilename_Response::operator =(
        UpdateFilename_Response&& x)
{

    m_success = x.m_success;

    return *this;
}

bool pcl_msgs::srv::UpdateFilename_Response::operator ==(
        const UpdateFilename_Response& x) const
{

    return (m_success == x.m_success);
}

bool pcl_msgs::srv::UpdateFilename_Response::operator !=(
        const UpdateFilename_Response& x) const
{
    return !(*this == x);
}

size_t pcl_msgs::srv::UpdateFilename_Response::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

size_t pcl_msgs::srv::UpdateFilename_Response::getCdrSerializedSize(
        const pcl_msgs::srv::UpdateFilename_Response& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

void pcl_msgs::srv::UpdateFilename_Response::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_success;

}

void pcl_msgs::srv::UpdateFilename_Response::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_success;
}

/*!
 * @brief This function sets a value in member success
 * @param _success New value for member success
 */
void pcl_msgs::srv::UpdateFilename_Response::success(
        bool _success)
{
    m_success = _success;
}

/*!
 * @brief This function returns the value of member success
 * @return Value of member success
 */
bool pcl_msgs::srv::UpdateFilename_Response::success() const
{
    return m_success;
}

/*!
 * @brief This function returns a reference to member success
 * @return Reference to member success
 */
bool& pcl_msgs::srv::UpdateFilename_Response::success()
{
    return m_success;
}


size_t pcl_msgs::srv::UpdateFilename_Response::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool pcl_msgs::srv::UpdateFilename_Response::isKeyDefined()
{
    return false;
}

void pcl_msgs::srv::UpdateFilename_Response::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}


