// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file JointState.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "JointState.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

pendulum_msgs::msg::JointState::JointState()
{
    // m_position com.eprosima.idl.parser.typecode.PrimitiveTypeCode@3967e60c
    m_position = 0.0;
    // m_velocity com.eprosima.idl.parser.typecode.PrimitiveTypeCode@60d8c9b7
    m_velocity = 0.0;
    // m_effort com.eprosima.idl.parser.typecode.PrimitiveTypeCode@48aaecc3
    m_effort = 0.0;

}

pendulum_msgs::msg::JointState::~JointState()
{


}

pendulum_msgs::msg::JointState::JointState(
        const JointState& x)
{
    m_position = x.m_position;
    m_velocity = x.m_velocity;
    m_effort = x.m_effort;
}

pendulum_msgs::msg::JointState::JointState(
        JointState&& x)
{
    m_position = x.m_position;
    m_velocity = x.m_velocity;
    m_effort = x.m_effort;
}

pendulum_msgs::msg::JointState& pendulum_msgs::msg::JointState::operator =(
        const JointState& x)
{

    m_position = x.m_position;
    m_velocity = x.m_velocity;
    m_effort = x.m_effort;

    return *this;
}

pendulum_msgs::msg::JointState& pendulum_msgs::msg::JointState::operator =(
        JointState&& x)
{

    m_position = x.m_position;
    m_velocity = x.m_velocity;
    m_effort = x.m_effort;

    return *this;
}

bool pendulum_msgs::msg::JointState::operator ==(
        const JointState& x) const
{

    return (m_position == x.m_position && m_velocity == x.m_velocity && m_effort == x.m_effort);
}

bool pendulum_msgs::msg::JointState::operator !=(
        const JointState& x) const
{
    return !(*this == x);
}

size_t pendulum_msgs::msg::JointState::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

size_t pendulum_msgs::msg::JointState::getCdrSerializedSize(
        const pendulum_msgs::msg::JointState& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

void pendulum_msgs::msg::JointState::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_position;
    scdr << m_velocity;
    scdr << m_effort;

}

void pendulum_msgs::msg::JointState::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_position;
    dcdr >> m_velocity;
    dcdr >> m_effort;
}

/*!
 * @brief This function sets a value in member position
 * @param _position New value for member position
 */
void pendulum_msgs::msg::JointState::position(
        double _position)
{
    m_position = _position;
}

/*!
 * @brief This function returns the value of member position
 * @return Value of member position
 */
double pendulum_msgs::msg::JointState::position() const
{
    return m_position;
}

/*!
 * @brief This function returns a reference to member position
 * @return Reference to member position
 */
double& pendulum_msgs::msg::JointState::position()
{
    return m_position;
}

/*!
 * @brief This function sets a value in member velocity
 * @param _velocity New value for member velocity
 */
void pendulum_msgs::msg::JointState::velocity(
        double _velocity)
{
    m_velocity = _velocity;
}

/*!
 * @brief This function returns the value of member velocity
 * @return Value of member velocity
 */
double pendulum_msgs::msg::JointState::velocity() const
{
    return m_velocity;
}

/*!
 * @brief This function returns a reference to member velocity
 * @return Reference to member velocity
 */
double& pendulum_msgs::msg::JointState::velocity()
{
    return m_velocity;
}

/*!
 * @brief This function sets a value in member effort
 * @param _effort New value for member effort
 */
void pendulum_msgs::msg::JointState::effort(
        double _effort)
{
    m_effort = _effort;
}

/*!
 * @brief This function returns the value of member effort
 * @return Value of member effort
 */
double pendulum_msgs::msg::JointState::effort() const
{
    return m_effort;
}

/*!
 * @brief This function returns a reference to member effort
 * @return Reference to member effort
 */
double& pendulum_msgs::msg::JointState::effort()
{
    return m_effort;
}


size_t pendulum_msgs::msg::JointState::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool pendulum_msgs::msg::JointState::isKeyDefined()
{
    return false;
}

void pendulum_msgs::msg::JointState::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
       
}


