// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file JointCommand.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_PENDULUM_MSGS_MSG_JOINTCOMMAND_H_
#define _FAST_DDS_GENERATED_PENDULUM_MSGS_MSG_JOINTCOMMAND_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(JointCommand_SOURCE)
#define JointCommand_DllAPI __declspec( dllexport )
#else
#define JointCommand_DllAPI __declspec( dllimport )
#endif // JointCommand_SOURCE
#else
#define JointCommand_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define JointCommand_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace pendulum_msgs {
    namespace msg {
        /*!
         * @brief This class represents the structure JointCommand defined by the user in the IDL file.
         * @ingroup JOINTCOMMAND
         */
        class JointCommand
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport JointCommand();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~JointCommand();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object pendulum_msgs::msg::JointCommand that will be copied.
             */
            eProsima_user_DllExport JointCommand(
                    const JointCommand& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object pendulum_msgs::msg::JointCommand that will be copied.
             */
            eProsima_user_DllExport JointCommand(
                    JointCommand&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object pendulum_msgs::msg::JointCommand that will be copied.
             */
            eProsima_user_DllExport JointCommand& operator =(
                    const JointCommand& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object pendulum_msgs::msg::JointCommand that will be copied.
             */
            eProsima_user_DllExport JointCommand& operator =(
                    JointCommand&& x);

            /*!
             * @brief Comparison operator.
             * @param x pendulum_msgs::msg::JointCommand object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const JointCommand& x) const;

            /*!
             * @brief Comparison operator.
             * @param x pendulum_msgs::msg::JointCommand object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const JointCommand& x) const;

            /*!
             * @brief This function sets a value in member position
             * @param _position New value for member position
             */
            eProsima_user_DllExport void position(
                    double _position);

            /*!
             * @brief This function returns the value of member position
             * @return Value of member position
             */
            eProsima_user_DllExport double position() const;

            /*!
             * @brief This function returns a reference to member position
             * @return Reference to member position
             */
            eProsima_user_DllExport double& position();


            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const pendulum_msgs::msg::JointCommand& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            double m_position;
        };
    } // namespace msg
} // namespace pendulum_msgs

#endif // _FAST_DDS_GENERATED_PENDULUM_MSGS_MSG_JOINTCOMMAND_H_